version: '3.8'

services:
  fastapi:
    build: .
    container_name: pv-fastapi
    restart: always
    ports:
      - "8887:8887"
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=sqlite:///./data/app.db
      - API_PREFIX=/apis/v1  # 添加这一行
    volumes:
      - ./data:/app/data