version: '3.8'

services:
  fastapi:
    build: .
    container_name: pv-fastapi
    restart: always
    ports:
      - "8887:8887"
    env_file:
      - ./backend/.env
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./backend:/app/backend
      - ./backend/app/database.db:/app/database.db