"""create account table

Revision ID: b81dcd9e4623
Revises: c614e00f9829
Create Date: 2026-02-08 17:45:56.323047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b81dcd9e4623'
down_revision: Union[str, Sequence[str], None] = 'c614e00f9829'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('age', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
