name: Deploy FastAPI

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.TX_HOST }}
          username: ${{ secrets.TX_USER }}
          key: ${{ secrets.TX_KEY }}
          source: "backend/"
          target: "/root/www/web/pv"

      - name: Run remote command
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.TX_KEY }}
          REMOTE_HOST: ${{ secrets.TX_HOST }}
          REMOTE_USER: ${{ secrets.TX_USER }}
          COMMAND: |
            cd /root/www/web/pv/backend
            uv venv
            uv pip sync requirements.txt
            pm2 restart fastapi || pm2 start .venv/bin/uvicorn --name fastapi -- main:app --host 0.0.0.0 --port 8887
            pm2 save