name: Deploy FastAPI to Server

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TX_HOST }}
          username: ${{ secrets.TX_USER }}
          key: ${{ secrets.TX_KEY }}
          script: |
            cd ~/www/github/pv
            # 放弃所有本地修改、删除所有新增文件
            git clean -fd
            git checkout -- .
            
            # 强制重置为远程最新代码（完全覆盖）
            git fetch origin
            git reset --hard origin/main
            
            docker-compose down -v --rmi all
            docker-compose up -d --build