name: Deploy Web

on:
  push:
    paths:
      - 'web/**'
    branches:
      - main

# 如果要用 GitHub Pages，需要这个权限
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: Install & Build
        working-directory: web
        env:
          VITE_API_URL: ${{ secrets.TX_PV_BE_URL }}/apis/v1
        run: |
          npm ci
          npm run build

      # 方案1：只部署到自己的服务器（推荐）
      - name: Upload to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.TX_HOST }}
          username: ${{ secrets.TX_USER }}
          key: ${{ secrets.TX_KEY }}
          source: "web/dist/"
          target: "/root/www/web/pv/web"